// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// 
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';


/// ```
/// 

class DefaultFirebaseOptions {


  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWyoB09ZwhW1fmgeLhoH_LIIF8-zlWqvQ',
    appId: '1:501448448370:web:315c924b2c490c096f65eb',
    messagingSenderId: '501448448370',
    projectId: 'steam-cd3ef',
    authDomain: 'steam-cd3ef.firebaseapp.com',
    databaseURL: 'https://steam-cd3ef-default-rtdb.firebaseio.com',
    storageBucket: 'steam-cd3ef.firebasestorage.app',
    measurementId: 'G-15JVGGPKFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8UYs5t0v8JwG0sSQVCvznwOz0LPwqzIg',
    appId: '1:501448448370:android:35cadb3773a919fb6f65eb',
    messagingSenderId: '501448448370',
    projectId: 'steam-cd3ef',
    databaseURL: 'https://steam-cd3ef-default-rtdb.firebaseio.com',
    storageBucket: 'steam-cd3ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl_Q_ZbtZdHKZqd0QQgBx411Jsf2cHaxY',
    appId: '1:501448448370:ios:34c9565b0188d01e6f65eb',
    messagingSenderId: '501448448370',
    projectId: 'steam-cd3ef',
    databaseURL: 'https://steam-cd3ef-default-rtdb.firebaseio.com',
    storageBucket: 'steam-cd3ef.firebasestorage.app',
    iosBundleId: 'com.example.demoFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl_Q_ZbtZdHKZqd0QQgBx411Jsf2cHaxY',
    appId: '1:501448448370:ios:34c9565b0188d01e6f65eb',
    messagingSenderId: '501448448370',
    projectId: 'steam-cd3ef',
    databaseURL: 'https://steam-cd3ef-default-rtdb.firebaseio.com',
    storageBucket: 'steam-cd3ef.firebasestorage.app',
    iosBundleId: 'com.example.demoFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWyoB09ZwhW1fmgeLhoH_LIIF8-zlWqvQ',
    appId: '1:501448448370:web:ea8b128550f3ca006f65eb',
    messagingSenderId: '501448448370',
    projectId: 'steam-cd3ef',
    authDomain: 'steam-cd3ef.firebaseapp.com',
    databaseURL: 'https://steam-cd3ef-default-rtdb.firebaseio.com',
    storageBucket: 'steam-cd3ef.firebasestorage.app',
    measurementId: 'G-4JE1XE47H7',
  );
}
